#!/bin/bash

# ----------------------------------------------------------------------
# qsub arguments
# ----------------------------------------------------------------------

#$  -N  shrub_pure_climat_modelling_highmem_wm
#$  -S  /bin/bash
#$  -l h_vmem=32G,highmem
#$  -l  h_rt=24:00:00
#$  -t  158-158
#$  -binding linear:1 ## core binding
## #$  -pe smp 1
## #$  -pe smp 1 ## this script seems not to work properly in parallel

# ---------------------------------------------------------------------- 
# output files
#
# Explanation:
#
#   USER          well, that is your user name
#   JOB_NAME      reference to the name of the job
#   JOB_ID        the unique ID of the job
#   TASK_ID       the task ID of the current task
# ----------------------------------------------------------------------

#$ -o /work/$USER/logfiles/$JOB_NAME-$JOB_ID-$TASK_ID.log
#$ -j y

# ----------------------------------------------------------------------
# actual processing
# ----------------------------------------------------------------------

paramsFile="none"
params=${SGE_TASK_ID}

echo
echo "task id: " ${SGE_TASK_ID}
echo "params file:" ${paramsFile}
echo "params: " ${params} 
echo
echo


source /etc/profile.d/000-modules.sh

module load geos gdal R
module unload cairo
module list

export JAVA_OPTS=${JAVA_OPTS:-"-Xmx256M -Xms16M"}

Rscript --no-restore --vanilla /home/georges/BRISCA/briscahub/scripts/1_pure_climate_modelling/shrubs_pure_climat_modelling_wm.R  ${params}
