#!/bin/bash

# ----------------------------------------------------------------------
# qsub arguments
# ----------------------------------------------------------------------

#$  -N  scabm                 ## campaign name
#$  -S  /bin/bash
#$  -l h_vmem=32G,highmem     ## the memory requested (here 32Go!!)
#$  -l  h_rt=24:00:00         ## the job wholetime
#$  -t  1-187                 ## the job to launch (get in R as job.id)
#$  -binding linear:1         ## core binding (for non-parallel jobs)
## #$  -pe smp 4              ## or the number of cpus for parallel jobs


# ---------------------------------------------------------------------- 
# output files
#
# Explanation:
#
#   USER          well, that is your user name
#   JOB_NAME      reference to the name of the job
#   JOB_ID        the unique ID of the job
#   TASK_ID       the task ID of the current task
# ----------------------------------------------------------------------

## where the logfiles are stored
#$ -o /work/$USER/logfiles/$JOB_NAME-$JOB_ID-$TASK_ID.log
#$ -j y

# ----------------------------------------------------------------------
# actual processing
# ----------------------------------------------------------------------

paramsFile="none"
params=${SGE_TASK_ID}

## print some job stats
echo
echo "task id: " ${SGE_TASK_ID}
echo "params file:" ${paramsFile}
echo "params: " ${params} 
echo
echo

## load the required modules
source /etc/profile.d/000-modules.sh
module load gdal geos R
export JAVA_OPTS=${JAVA_OPTS:-"-Xmx256M -Xms16M"} ## for MAXENT

## launch the R script
Rscript --no-restore --vanilla ~/BRISCA/briscahub/scripts/3_climate_and_biointer_modelling/shrubs_climat_and_biointer_modelling.R  ${params}
