#!/bin/bash

# ----------------------------------------------------------------------
# qsub arguments
# ----------------------------------------------------------------------

#$  -N  scabp
#$  -S  /bin/bash
#$  -l  h_vmem=5999M
## #$  -l  h_vmem=9999M
## #$  -l  h_vmem=20G,highmem
#$  -l  h_rt=15:00:00
## #$  -t  1-10962
#$  -t 1-3500
#$  -binding linear:1 ## core binding

# ---------------------------------------------------------------------- 
# output files
#
# Explanation:
#
#   USER          well, that is your user name
#   JOB_NAME      reference to the name of the job
#   JOB_ID        the unique ID of the job
#   TASK_ID       the task ID of the current task
# ----------------------------------------------------------------------

#$ -o /work/$USER/logfiles/$JOB_NAME-$JOB_ID-$TASK_ID.log
#$ -j y

# ----------------------------------------------------------------------
# actual processing
# ----------------------------------------------------------------------

paramsFile="none"
params=${SGE_TASK_ID}

echo
echo "task id: " ${SGE_TASK_ID}
echo "params file:" ${paramsFile}
echo "params: " ${params} 
echo
echo


source /etc/profile.d/000-modules.sh

module load gdal R/3.1.0-3
module unload cairo
module list

export JAVA_OPTS=${JAVA_OPTS:-"-Xmx256M -Xms16M"}

Rscript --no-restore --vanilla ~/BRISCA/briscahub/scripts/3_climate_and_biointer_modelling/shrubs_climat_and_biointer_projections.R  ${params}
