---
title: "BRISCA_WorkFlow"
author: "Damien G."
date: "17 February 2017"
output: html_document
---

Here is described the script workflow that have been used for BRISCA project as a kind of log file.

This is the new 2017 workflow cause we discovered some glitch in species occ definition and almost
everithing have to be done from scratch!


## January 2017

1. Anne has corrected input data for 22 species that have fake presences (xx/01/2017)

## February 2017

1. run the Thining process for the 22 species on presences (13/02/2017)

2. generate the thined pseudo absences for our 22 species (14/02/2017)

3. do the pure climate modelling, projection and ensemble projections for every the species (10/03/2017) (have been redone entirerly because I dicovered some stanges (due to an unknow bug) stripes in couple of models projection maps)

4. produce some graphs to check the validity of projected models and send it to Anne and Signe for a visual check (23/02/2017)

5. construct the present day filter masks (current binaries projection with convexhull + 250m buffer) (17/03/2017)

7. create biotic interaction masks

5. copy the pure climate models outputs in /data/idiv_sdiv/ (27/02/2017)

## March 2017

Re-run everithing again!
