#!/bin/bash

# ----------------------------------------------------------------------
# qsub arguments
# ----------------------------------------------------------------------

#$  -N  shrub_pure_climat_modelling_highmem
#$  -S  /bin/bash
## #$  -l  h_vmem=9999M
#$ -l h_vmem=17G,highmem
#$  -l  h_rt=24:00:00
#$  -t  1-199
#$  -binding linear:1 ## core binding
## #$  -pe smp 1
## #$  -pe smp 1 ## this script seems not to work properly in parallel

# ---------------------------------------------------------------------- 
# output files
#
# Explanation:
#
#   USER          well, that is your user name
#   JOB_NAME      reference to the name of the job
#   JOB_ID        the unique ID of the job
#   TASK_ID       the task ID of the current task
# ----------------------------------------------------------------------

#$ -o /work/$USER/logfiles/$JOB_NAME-$JOB_ID-$TASK_ID.log
#$ -j y

# ----------------------------------------------------------------------
# actual processing
# ----------------------------------------------------------------------

paramsFile="none"
params=${SGE_TASK_ID}

echo
echo "task id: " ${SGE_TASK_ID}
echo "params file:" ${paramsFile}
echo "params: " ${params} 
echo
echo


source /etc/profile.d/000-modules.sh

module load gdal R
module unload cairo
##module load jdk
module load scala/2.11

module list

export JAVA_OPTS=${JAVA_OPTS:-"-Xmx256M -Xms16M"}

java -version
scala -e 'val fonts = sun.awt.X11FontManager.getInstance.getFontPathNative(true)
println(fonts)
'

## R CMD BATCH --no-restore --vanilla "--args ${params}" ~/SHRUBS/ShrubHub/scripts/users/dgeorges/ndvi_growth_chronologies_cor/cor_mcd43a4_growth_chrono.R /dev/out
Rscript --no-restore --vanilla ~/BRISCA/briscahub/scripts/shrubs_pure_climat_modelling.R  ${params}
